require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - test/**/*

Layout/BlockAlignment:
  EnforcedStyleAlignWith: 'start_of_block'

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 25

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false
