version: '3'
services:
  health_cards:
    build:
      context: .
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE="${HEALTH_CARDS_SECRET_KEY_BASE}"
      - HOST="${HEALTH_CARDS_HOST}"
      - PORT=3000
    expose:
      - "3000"
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    # Debug Mode
    command: [nginx, '-g', 'daemon off;']