#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'health_cards'

key = HealthCards::PrivateKey.generate_key
key.to_jwk

issuer = HealthCards::Issuer.new(key: key, url: 'http://example.com')

jws = issuer.issue_jws(FHIR::Bundle.new)
hc = issuer.issue_health_card(FHIR::Bundle.new)

jws.verify

ver = HealthCards::Verifier.new(keys: key.public_key)
ver.verify(jws)

card = HealthCards::HealthCard.new(jws.to_s)
card.to_json

ver.verify(hc)
ver.verify(card)

codes = HealthCards::QRCodes.from_jws(jws.to_s)
codes.chunks.map(&:data)

codes.to_jws

puts 'Success!'
