default: &default
  resourceType: CapabilityStatement
  status: active
  fhirVersion: 4.0.1
  format: [application/fhir+json]
  rest:
    - mode: server
      resource:
        - type: Patient
          operation:
          - name: health-cards-issue
            definition: OperationDefinition/health-cards-issue

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
