default: &default
  authorization_endpoint: https://ehr.example.com/auth/authorize
  token_endpoint: https://ehr.example.com/auth/token
  token_endpoint_auth_methods_supported: [client_secret_basic]
  scopes_supported: [launch/patient, patient/Immunization.read]
  response_types_supported: [code, code id_token, id_token, refresh_token]
  capabilities: [health-cards]

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default