# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in health_cards.gemspec
gemspec

gem 'rake', '~> 13.0'

# Gems used for testing
gem 'activesupport', '~>6.1.3.2'
gem 'minitest', '~> 5.14'
gem 'webmock'

# Linting and Styling
gem 'rubocop', '~> 1.14'
gem 'rubocop-minitest', '~> 0.10.1', require: false
gem 'rubocop-rake', '~> 0.5.1'
