# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rake/testtask'
require 'rubocop/rake_task'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/*_test.rb', 'test/**/*_spec.rb']
  t.verbose = false
  t.warning = false
end

desc 'Run RuboCop'
task :rubocop do
  RuboCop::RakeTask.new(:rubocop) do |t|
    t.options = %w[-c .rubocop.yml]
  end
end

task default: %i[test rubocop]