name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [ 2.7.4 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        # uses: ruby/setup-ruby@v1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.4']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Install js dependencies
      run: yarn install
    - name: Run webpack
      run: ./bin/rake webpacker:install:react
    - name: Run tests
      run: bundle exec rake
    - name: Codecov
      uses: codecov/codecov-action@v1.5.2


  lint:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.4']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Rubocop
      run: bundle exec rubocop
